apiVersion: v1
kind: Service
annotations:
  service.beta.kubernetes.io/aws-load-balancer-type: nlb
metadata:
  name: microservice
  labels:
    app: microservice
spec:
  ports:
  - port: 80
    targetPort: http-port
  selector:
    app: microservice
  type: LoadBalancer