---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: microservice
spec:
  ports:
  - port: 31001
    nodePort: 31001
    targetPort: http-port
    protocol: TCP
  selector:
    app: microservice
  type: NodePort